### PR TITLE
Check on empty port implemented

### PR DESCRIPTION
**Pull request by Frogli**
Implemented a check to prevent a port 0 to be added tot the hostUrl

### CODE REVIEW

**Comment by dimitri-koenig** [comment]
Hi Frogli

Sorry for bugging you, but having a https host with no port = port 80 doesn't work.
What do you think about simply avoiding the port data if there isn't any?

**Comment by Frogli** [comment]
Hi Dimitri,

Yeah sorry my bad. I have that in a later version. The copy past error….

grtz Henk

**Comment by Frogli** [comment]
Fixed it.

**Comment by dimitri-koenig** [comment]
You're awesome, thx.

**Comment by Frogli** [comment]
Tnx! Btw will you also correct this in the Jira workflow. It has the same problem I believe.

**Comment by dimitri-koenig** [comment]
I took your code and implemented it, thx

**Pull request merged**
